version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  target-branch: main
- package-ecosystem: github-actions
  directory: "/"
  target-branch: main
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: "/"
  target-branch: main
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/"
  target-branch: main
  schedule:
    interval: daily
