name: Trigger

on:
  schedule:
    - cron:  '0 5 * * *'

  workflow_dispatch:

jobs:
  Trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check if fishnet has an update
        run: scripts/check-upstream lichess-org/fishnet master
