name: Trigger

on: 
  workflow_dispatch

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  Trigger:
    runs-on: ubuntu-latest
    env:
      JOB_NAME: "Check if fishnet has an update"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check if fishnet has an update
        run: curl -s https://api.github.com/repos/lichess-org/fishnet/commits/master | jq -r "((now - (.commit.author.date | fromdateiso8601) )  / (60*60*24)  | trunc)"
        shell: bash
